### ISSUE TITLE
change built-in chimes

### ISSUE THREAD

**Issue by lustyffh** [pauln/esphome-linp-doorbell-g03#3]
Hi, firstly thanks a lot for this piece of work. I'm not into embedded programming to such a degree as to be able to reverse engineer all the quirks in this thing. Therefore I'm so grateful that there's an HA integration already available.

My question is rather about usability. I wonder if it's possible to change built-in chimes? I assume it can be done via raw programming of STM8S005K6.  Any clues on where to dig to find something more about it?

**Comment by pauln** [comment]
Hi,
Unfortunately, I don't think that it's possible to implement custom chimes, as they're actually handled by a separate chip (`FR0396-E2`), which has them baked in from the factory. I haven't found much information on it other than a [Chinese FR0396-E2 datasheet](http://www.sizeyuan.cn/wp-content/uploads/2018/06/F2-36s8hxmlxp.pdf), which doesn't seem to suggest that it can do anything other than play the various built-in chimes at a few volume levels and flash an LED at 3Hz.

The speaker is directly connected to this chip - not the `STM8S005K6` (or the `ESP32`).  As such, you'd have to make hardware modifications - at which point you might be better off looking at the [`dfplayer` esphome component](https://esphome.io/components/dfplayer.html).  You could probably unplug the speaker from the original board and connect it to a DF-Player mini, connect it to the `ESP32` and trigger the DF-Player from ESPHome directly; the STM and FR0396 would still do their thing, but wouldn't make any noise since you've taken the speaker away...
