### ISSUE TITLE
compilation warning - Unexpected property received

### ISSUE THREAD

**Issue by lustyffh** [pauln/esphome-linp-doorbell-g03#7]
Hi,

I'm getting the following warning during compilation. However, it completes successfully. What does it mean and if I have to worry about it?

```
src\linp-doorbell.h: In member function 'String LinpDoorbell::handleMessage(String)':

src/esphome/core/log.h:101:99: warning: format '%s' expects argument of type 'char*', but argument 5 has type 'String*' [-Wformat=]

   esp_log_printf_(ESPHOME_LOG_LEVEL_INFO, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)

                                                                                                   ^

src/esphome/core/log.h:146:28: note: in expansion of macro 'esph_log_i'

 #define ESP_LOGI(tag, ...) esph_log_i(tag, __VA_ARGS__)

                            ^

src\linp-doorbell.h:126:11: note: in expansion of macro 'ESP_LOGI'

           ESP_LOGI("linp-doorbell", "Unexpected property received: %s", value);

           ^

```

**Comment by pauln** [comment]
Sorry for the slow response.  That warning was because I wasn't converting the `value` to the right type of string for the log function.

It shouldn't have caused any problems, as that specific log entry only gets written if something weird goes on with the communication between the ESP32 and the other microcontroller.  If that were to happen, I'm guessing the worst that would happen is the ESP32 would restart, which might help it re-sync with the other micro anyway.
