### ISSUE TITLE
What pins do I need to pull to ground.

### ISSUE THREAD

**Issue by DirkTas67** [pauln/esphome-linp-doorbell-g03#8]
Can you explain to me what pins I need to pull to ground?
[Picture of the ESP](https://photos.app.goo.gl/RXzQk2Ccdu3rAYL48)

**Comment by pauln** [comment]
@DirkTas67 The two pins you've marked with red are the ones which need to be pulled to ground while powering up in order to enter flashing mode.  Once you've flashed it, disconnect those pins from ground and power cycle the doorbell to perform a normal boot - it should then connect to your wifi network using the details you set in your YAML config, and you'll be able to add it to Home Assistant.

**Comment by fantomnotabene** [comment]
Just to clear things
![photo_2020-04-14 22 18 56](https://user-images.githubusercontent.com/9576189/79264946-04484880-7e9e-11ea-8f04-17d959265fba.jpeg)
![photo_2020-04-14 22 19 01](https://user-images.githubusercontent.com/9576189/79264949-07433900-7e9e-11ea-8d1f-4f08a7cb01d0.jpeg)
